### ISSUE TITLE
double_float min(), max(), and lowest() numeric limits

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#75] opened 2021-08-08 11:26 UTC
Similar to the larger discussiong from #21, we will in this issue be handling the proper dimmensioning of `min()`, `max()`, and `lowest()` in the specialization of `std::numeric limits<number<cpp_double_float<>, ExprTemplates>`.

**Comment by sinandredemption** [comment] 2021-08-09 06:37
Hello @ckormanyos 

I just went through the David Bailey's QD package, and found the following interesting constants:
```
const double dd_real::_eps = 4.93038065763132e-32;  // 2^-104
const double dd_real::_min_normalized = 2.0041683600089728e-292;  // = 2^(-1022 + 53)
const dd_real dd_real::_max = 
    dd_real(1.79769313486231570815e+308, 9.97920154767359795037e+291);
const dd_real dd_real::_safe_max = 
    dd_real(1.7976931080746007281e+308, 9.97920154767359795037e+291);
const int dd_real::_ndigits = 31;
```

Since our algorithms are virtually identical to that of QD, I would imagine these values to work for us as well.

**Comment by ckormanyos** [comment] 2021-08-09 06:52
> David Bailey's QD package, and found the following interesting constants

Nice research result Fahad. Thanks for that.

Isn't that interesting, he settles on 104 binary digits for `double_double`'s value of `epsilon()`. We ended up taking 106.

I wonder if the mathematical method to produce the two components of `dd_real::_max` are known. We would need some kind of a general formula because we instantiate for `float`, `double`, `long` `double`, and `boost::multiprecision::float128` constituents.

I'm having trouble figuring out how the first and second components of the maximum are related to each other in the numerical sense and also how these are derived from the underlying floating-point constituent type.

@sinandredemption and @cosurgi

**Comment by sinandredemption** [comment] 2021-08-09 07:27
> I'm having trouble figuring out how the first and second components of the maximum are related to each other in the numerical sense and also how these are derived from the underlying floating-point constituent type.

The first component is simply `numeric_limits<double>::max`, and the second component is again `max` shifted right by 53 bits (size of mantissa of double), so that the pair satisfies the property `n1 <= 0.5 * ulp(n0)`

**Comment by ckormanyos** [comment] 2021-08-09 07:29
> first component is simply `numeric_limits<double>::max`, and the second component is again max shifted right by 53 bits (size of mantissa of double),

That makes sense, so not the sum of these, but rather the pair of constituent type(s).

**Comment by sinandredemption** [comment] 2021-08-09 07:29
Notice that we can't do the above trick with `min()` since we will run in to subnormal range while right-shifting. This creates an asymmetry in exponent range representable by `cpp_double_float<>`, which I just noticed that we haven't reflected in `numeric_limits<>` yet. I am working on this.

**Comment by ckormanyos** [comment] 2021-08-09 07:30
> he settles on 104 binary digits for double_double's value of `epsilon()`. We ended up taking 106.

This comment is incorrect. For `epsilon()` we took the practical value of `digits - n` binary digits, where `n` is a small integral value to be determined.

**Comment by ckormanyos** [comment] 2021-08-09 07:33
> Notice that we can't do the above trick with `min()` since we will run in to subnormal range while right-shifting. This creates an asymmetry in exponent range representable by `cpp_double_float<>`, which I just noticed that we haven't reflected in numeric_limits<> yet. I am working on this.

Right on! I would like to see that when you get it!

In fact, there are several interesting test cases still commented out [here](https://github.com/BoostGSoC21/multiprecision/blob/452ebc804836621a30b2086267d888bc71070027/test/test_exp.cpp#L211) in `test_exp.cpp` regarding the non-correct/non-tuned values of min/max in relation to each other. I'd like to see if, when you correct min/max in limits, these test cases pass or if we need new thresholds for tolerances or test values are needed on the `test_exp.cpp`-level.

**Comment by sinandredemption** [comment] 2021-08-09 07:43
> For epsilon() we took the practical value of digits - n binary digits, where n is a small integral value to be determined.

What is more interesting is that we can take a practical value of _exactly_ `digits` binary digits for `cpp_quad_float<>` in the basic arithmetic operations. This can mean that if we somehow efficiently extract only the upper two parts of a `cpp_quad_float<>`, we can achieve theoretically IEEE754-like correctness.

**Comment by ckormanyos** [comment] 2021-08-09 08:06
> What is more interesting is that we can take a practical value of exactly digits binary digits for `cpp_quad_float<>` in the basic arithmetic operations. This can mean that if we somehow efficiently extract only the upper two parts of a `cpp_quad_float<>`

Yes. At the moment, it is a bit of a challenge to get it all working with double/quad-float. When we fiddle around with min/max, we probably also need to look into a few other areas such as infinity, etc. I have not yet looked into all of these, but it really will pay off to get `limits` properly dimensioned --- even though it will take a bit more work yet...

**Comment by cosurgi** [comment] 2021-08-09 19:27
> The first component is simply numeric_limits<double>::max, and the second component is again max shifted right by 53 bits (size of mantissa of double), so that the pair satisfies the property n1 <= 0.5 * ulp(n0)
[…]
> Notice that we can't do the above trick with min() since we will run in to subnormal range while right-shifting. 

Yes. I think this is a good description of both max and min:

1. max components are { LimbType::max , LimbType::max shifted down by numeric_limit::digits }
2. min components are { LimbType::min  shifted up by numeric_limit::digits , 0 }
3. lowest should be -max, I suppose.
4. about epsilon so far we agreed on ldexp(1, 4 - digits) in #21. But question: if we define epsilon such that all the + - / * sqrt tests pass it, did the most recent test results modify this value to be larger? (maybe it will be changed if we swap some algorithms to those in that paper which I sent recently). And also - Bailey used `ldexp(1 , 2 - digits)` which is 4.93038065763132e-32. I prefer by just a little bit ours, a little larger value. But it is not exactly as per definition of 1+epsilon : the next number right above 1.

>    const double dd_real::_eps = 4.93038065763132e-32;  // 2^-104
>    const double dd_real::_min_normalized = 2.0041683600089728e-292;  // = 2^(-1022 + 53)
>    const dd_real dd_real::_max = 
>        dd_real(1.79769313486231570815e+308, 9.97920154767359795037e+291);
>    const dd_real dd_real::_safe_max = 
>        dd_real(1.7976931080746007281e+308, 9.97920154767359795037e+291);
>    const int dd_real::_ndigits = 31;


I wanted to see if I could reproduce these values in a straightforward way and wrote the code (pasted below) which produces:

```
--------- float ---------
max    : 3.402823466385e+38
min    : 1.175494350822e-38
lowest : -3.402823466385e+38
epsilon: 1.192092895508e-07
--------- double_float of: float ---------
max    : { 3.402823466385e+38,1.014120419736e+31 }
min    : { 1.972152263053e-31,0 }
lowest : { -3.402823466385e+38,-1.014120419736e+31 }
epsilon: { 5.684341886081e-14,0 }

--------- double ---------
max    : 1.79769313486231570815e+308
min    : 2.22507385850720138309e-308
lowest : -1.79769313486231570815e+308
epsilon: 2.22044604925031308085e-16
--------- double_float of: double ---------
max    : { 1.79769313486231570815e+308,9.97920154767359795037e+291 }
min    : { 2.004168360008972778e-292,0 }
lowest : { -1.79769313486231570815e+308,-9.97920154767359795037e+291 }
epsilon: { 1.97215226305252951353e-31,0 }

--------- long double ---------
max    : 1.189731495357231765021264e+4932
min    : 3.362103143112093506262678e-4932
lowest : -1.189731495357231765021264e+4932
epsilon: 1.084202172485504434007453e-19
--------- double_float of: long double ---------
max    : { 1.189731495357231765021264e+4932,3.224773679851846279544253e+4912 }
min    : { 6.201985623040326737962671e-4913,0 }
lowest : { -1.189731495357231765021264e+4932,-3.224773679851846279544253e+4912 }
epsilon: { 4.701977403289150031874946e-38,0 }

--------- boost::multiprecision::number<boost::multiprecision::backends::float128_backend, (boost::multiprecision::expression_template_option)0> ---------
max    : 1.189731495357231765085759326628007016196e+4932
min    : 3.362103143112093506262677817321752602598e-4932
lowest : -1.189731495357231765085759326628007016196e+4932
epsilon: 1.925929944387235853055977942584927318538e-34
--------- double_float of: boost::multiprecision::number<boost::multiprecision::backends::float128_backend, (boost::multiprecision::expression_template_option)0> ---------
max    : { 1.189731495357231765085759326628007016196e+4932,5.728348781722740809597148796851054337301e+4897 }
min    : { 3.491407517610198621055094847499003565891e-4898,0 }
lowest : { -1.189731495357231765085759326628007016196e+4932,-5.728348781722740809597148796851054337301e+4897 }
epsilon: { 1.483682460274968554292694104619055805347e-67,0 }
```


Please experiment with this code:

```
#include <boost/config.hpp>
#include <boost/cstdfloat.hpp>
#include <iostream>
#include <limits>
#include <boost/multiprecision/float128.hpp>
#include <boost/core/demangle.hpp>

template<typename T>
void print_limits() {
	std::cout << "--------- " << boost::core::demangle(typeid(T).name())<< " ---------" << std::endl;
	std::cout << std::setprecision(std::numeric_limits<T>::max_digits10+4);
	std::cout << "max    : "<< std::numeric_limits<T>::max()     << std::endl;
	std::cout << "min    : "<< std::numeric_limits<T>::min()     << std::endl;
	std::cout << "lowest : "<< std::numeric_limits<T>::lowest()  << std::endl;
	std::cout << "epsilon: "<< std::numeric_limits<T>::epsilon() << std::endl;
	using std::pow;
	using std::ldexp;
	auto dig_base           = std::numeric_limits<T>::digits;
	auto pow2_digits        = pow(T(2),dig_base);
	auto pow2_digits_plus_1 = pow(T(2),dig_base+1);
	std::cout << "--------- double_float of: "     << boost::core::demangle(typeid(T).name())<< " ---------" << std::endl;
	std::cout << "max    : { " << std::numeric_limits<T>::max()                          <<","<< (std::numeric_limits<T>::max() / pow2_digits_plus_1    ) << " }" << std::endl;
	std::cout << "min    : { " << (std::numeric_limits<T>::min() * pow2_digits        )  <<","<< 0                                                        << " }" << std::endl;
	std::cout << "lowest : { " << (-std::numeric_limits<T>::max())                       <<","<< (-(std::numeric_limits<T>::max() / pow2_digits_plus_1 )) << " }" << std::endl;
	std::cout << "epsilon: { " << ldexp(1 , 4 - 2*dig_base)                              <<","<< 0                                                        << " }" << std::endl;
	std::cout << std::endl;
}
int main() {
	print_limits<float>();
	print_limits<double>();
	print_limits<long double>();
	print_limits<boost::multiprecision::float128>();
}
```

Also I notice that Bailey used `max_digits10 + 4` which is kinda superfluous. But warranted due to the can of worms experience mentioned by @jzmaddock

**Comment by ckormanyos** [comment] 2021-08-10 06:11
> see if I could reproduce these values in a straightforward way

Yeah, what we eventually need is width-independent code that produces the values of `min()`, `max()` and `epsilon()`, regardless of whether or not the underlying type is 4, 8, 10 or 16 bytes in width. _Also_ in a later step adhering to C++11 `constexpr`-ness.

At first, i would like to see these values expressed with constituent pairs using, for instance, the built-in `ldexp` function. When the numerical aspects of these limits work out and all the tests pass, we can either use (from boost) or write our simple own copy of a `constexpr`-ified function `my_ldexp()` or similar.

**Comment by ckormanyos** [comment] 2021-08-10 06:15
> so far we agreed on `ldexp(1, 4 - digits)`

I am not really concerned with the exact number of bits we subtract from the maximum allowed level. We can take `n - digits` with `n` having value 2 or 4. If we drop down to `2 - digits`, then we will need to be sure to modify the limits of our homegrown add/sub/mul/div/sqrt tests and also ensure that all the Boost-style tests pass. That is relatively straightforward.

**Comment by sinandredemption** [comment] 2021-08-13 12:06
Progress on this was made in #77 (and #79 as well), both of which are merged into `develop`

I think I'll close this issue for now and we can reopen anytime a new problem arises. The discussion around `digits` has it's own separate issue (#21)

**Closed as completed by sinandredemption** 2021-08-13 12:06 UTC
Labels: help wanted, requirement
