### ISSUE TITLE
double_float handle numeric_limits epsilon if not yet finished

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#24] opened 2021-07-19 07:43 UTC
Remember to properly handle `std::numeric_limits<double_float<T>>::epsilon()` properly if this has not been done yet.

**Comment by sinandredemption** [comment] 2021-07-19 07:47
It appears Janek [has handled this](https://github.com/BoostGSoC21/multiprecision/pull/23/files#diff-bb9459c4a1f6866e23101b1428b9f6a910b63310156b202b3946d414fcb92071R1157) in his branch which will be merged as soon as I review the changes done in detail.

**Comment by ckormanyos** [comment] 2021-07-19 08:08
> It appears Janek has handled this in his branch which will be merged as soon as I review the changes done in detail.

Cool.

Also, I was wondering if refinements of the `epsilon()` member of numeric limits could be related to tolerances on certain test cases failing in CI? I need to establish if this could be relevant here via checking exactly how the tolerances are handled in the arithmetic tests.

**Comment by sinandredemption** [comment] 2021-07-19 09:26
>  I need to establish if this could be relevant here via checking exactly how the tolerances are handled in the arithmetic tests.

I think not. See [this line](https://github.com/BoostGSoC21/multiprecision/blob/f0ff7a09a8c75d38619e087a799f578a399dfffb/test/test_cpp_double_float_arithmetic.cpp#L89) from test_cpp_double_float_arithmetic.cpp:

> `const control_float_type MaxError = boost::multiprecision::ldexp(control_float_type(1), -std::numeric_limits<naked_double_float_type>::digits);`

If everything is going as intended, `MaxError` shouldn't depend on `epsilon()`. And the test deviation is checked relative to `MaxError` (see [this line](https://github.com/BoostGSoC21/multiprecision/blob/f0ff7a09a8c75d38619e087a799f578a399dfffb/test/test_cpp_double_float_arithmetic.cpp#L138)):

> `if (delta > MaxError) {`
> `   ...`
> `}`

**Comment by ckormanyos** [comment] 2021-07-19 15:36
> If everything is going as intended, `MaxError` shouldn't depend on `epsilon()`. And the test deviation is checked relative to `MaxError`

OK. I kind of lost the state of affairs in all the action regarding the `digits` member(s) of `std::numeric_limits<double_gloat<T>>`. @sinandredemption in your opinion, are we sure to be using the right value(s) for digits now?

@cosurgi

**Comment by sinandredemption** [comment] 2021-07-21 11:34
@ckormanyos IMHO, yes, but my opinion is based on empirical information that the arithmetic tests seem to pass for the current values. Maybe @cosurgi can add more to this.

**Comment by ckormanyos** [comment] 2021-07-21 12:05
>  the arithmetic tests seem to pass for the current values

Hi @sinandredemption which branch is up to date with these values? I have found in other experiments that if the number of test cases per arithmetic operation is increased from 10,000 to, let's say, a few million, then failures arise eventually.

The failures that I find are those needing one single bit more tolerance from `ldexp` on mul/div, but not on add/sub.

I also tried my old algorithms from around 20 years ago and these also need one extra bit tolerance on mul/div.

**Comment by sinandredemption** [comment] 2021-07-21 15:42
> which branch is up to date with these values?

I'm afraid that no branch currently passes all the arithmetic tests (with millions of test cases as you pointed out).

> I also tried my old algorithms from around 20 years ago and these also need one extra bit tolerance on mul/div.

As soon as I get back, I would check David Bailey's QD package's behavior on the issue (which should in theory be identical to cpp_double_float<>)

**Comment by ckormanyos** [comment] 2021-07-21 16:21
> check David Bailey's QD package's behavior on the issue

Good idea.

The original work in the C language (at least as far as I am aware) was from a professor named Keit Briggs. Briggs' famous `double-double` formed the basis for this stuff. Anyway, my original `q_float` work from early in this century used frameworks from the algorithms of Briggs. If you pull up ma `q_float` example VisualStudio Project in my branch, you will find that I have adapted the tests to be almost identical with yours in this GSoC work. I found that I needed 2 least-sibnificant bits to pass mul/div using the original Briggs algos. Although I do admit, however, that I did optimize Briggs' work. All of add/sub, sqrt pass the tests on millions of trials (Briggs algos) with 1 least significant bit.

My tests on the unrelated, but interesting `q_float`work of mine can be found newly [here](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_chris_modify_and_test/example/q_float/test.cpp). You can see the use of 2 LSB, for instance, [here](https://github.com/BoostGSoC21/multiprecision/blob/930111f69a89258de05a35844566ac2ab9328d0f/example/q_float/test.cpp#L370).

**Comment by ckormanyos** [comment] 2021-07-27 20:14
Hi @sinandredemption and @cosurgi

Have we resolved the proper values for the `epsilon()` member(s) of `std::numeric_limits<boost::multiprecision::backends::cpp_double_float<T>>` yet? It appears as though some branches like mine are using the epsilon from the underlying low/high parts. But I'm not sure if this is right. I think also `min`, `max` and `lowest` and maybe some others might need some tuning/redesign...

**Comment by sinandredemption** [comment] 2021-07-27 20:23
> Have we resolved the proper values for the epsilon() member(s) of std::numeric_limits<boost::multiprecision::backends::cpp_double_float<T>> yet?

I am afraid, not yet. Intuitively, it should be equal to `ldexp(1, -digits)` or so? Please correct me if I'm mistaken.

> I think also min, max and lowest and maybe some others might need some tuning/redesign...

Agreed. They must be scaled down so that they fit within the bounds set by max_exponent, min_exponent.

**Comment by ckormanyos** [comment] 2021-07-29 15:21
@sinandredemption I believe your/our recent work handled this. If you like, ... close this. Also if you like, feel free to open another new issue on retrieving as much `constexpr`-correctness as possible from limits, constructors, arithmetic ops, etc.

**Comment by sinandredemption** [comment] 2021-07-29 15:23
@ckormanyos Sure! Let me do it right away.

**Closed as completed by sinandredemption** 2021-07-29 15:23 UTC
